# Identifiant unique du projet
sonar.projectKey=ilyesalili_confplan_00967903-bf77-4e16-9136-445cbf30287f

# L'URL du serveur (obligatoire pour éviter l'erreur localhost:9000)
# Si vous utilisez SonarCloud :
sonar.host.url=https://sonarcloud.io

# Si vous utilisez SonarCloud, vous devez aussi spécifier votre organisation
# sonar.organization=votre_nom_organisation

# Emplacement du code source
sonar.sources=.
sonar.sourceEncoding=UTF-8
